spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 19920308
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimumIdle: 10
      maximumPoolSize: 20
      idleTimeout: 500000
      maxLifetime: 540000
      connectionTimeout: 60000
      connectionTestQuery: SELECT 1

dubbo:
  scan:
    base-packages: com.example.mall.user.service
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://127.0.0.1:8848?namespace=a4fb7fdd-b752-438a-bd66-75b9523d7633
  protocol:
    name: dubbo
