mybatis-plus:
  mapper-locations: classpath:/dal/mapper/*Mapper.xml
  type-aliases-package: com.example.mall.user.dal.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false